import type {
  Alert,
  Analytics,
  ChatMessage,
  Customer,
  FraudReport,
  FraudRule,
  RecentAlert,
  RiskFactor,
  RiskTrendItem,
  Transaction,
} from './types';

const defaultFactors = [
  {
    title: 'High Transaction Amount',
    detail: 'Amount is significantly above this user’s median historical spend.',
    impact: 'high' as const,
  },
  {
    title: 'Unusual Location Discrepancy',
    detail: 'Transaction initiated from a geo-location 1,420 km from previous login.',
    impact: 'medium' as const,
  },
  {
    title: 'Velocity Threshold Triggered',
    detail: '4 distinct transactions attempted within 3 minutes on this card.',
    impact: 'high' as const,
  },
  {
    title: 'Unrecognized Device Fingerprint',
    detail: 'Browser user agent and device ID not in authorized user profiles.',
    impact: 'low' as const,
  },
];

export const transactions: Transaction[] = [
  {
    id: 'TXN_829392',
    amount: 245000,
    prediction: 'Fraud',
    fraudProbability: 92.4,
    anomalyScore: 0.88,
    riskScore: 92,
    riskLevel: 'HIGH',
    timestamp: '2025-08-23T18:39:00Z',
    modelVersion: 'FG-4.2.1-PROD',
    customer: 'Aarav Sharma',
    location: 'Mumbai, IN',
    paymentMethod: 'HDFC Credit Card (..4921)',
    device: 'Unknown Linux Device',
    factors: [defaultFactors[0], defaultFactors[1]],
  },
  {
    id: 'TXN_829391',
    amount: 75000,
    prediction: 'Fraud',
    fraudProbability: 74.6,
    anomalyScore: 0.71,
    riskScore: 75,
    riskLevel: 'MEDIUM',
    timestamp: '2025-08-23T18:33:00Z',
    modelVersion: 'FG-4.2.1-PROD',
    customer: 'Rohan Mehta',
    location: 'Bengaluru, IN',
    paymentMethod: 'ICICI NetBanking',
    device: 'OnePlus 11 (Android 14)',
    factors: [defaultFactors[2]],
  },
  {
    id: 'TXN_829390',
    amount: 120000,
    prediction: 'Fraud',
    fraudProbability: 68.2,
    anomalyScore: 0.64,
    riskScore: 68,
    riskLevel: 'MEDIUM',
    timestamp: '2025-08-23T18:26:00Z',
    modelVersion: 'FG-4.2.1-PROD',
    customer: 'Priya Nair',
    location: 'Dubai, UAE',
    paymentMethod: 'SBI International Visa',
    device: 'Safari on macOS',
    factors: [defaultFactors[1]],
  },
  {
    id: 'TXN_829389',
    amount: 4200,
    prediction: 'Legitimate',
    fraudProbability: 8.1,
    anomalyScore: 0.09,
    riskScore: 12,
    riskLevel: 'LOW',
    timestamp: '2025-08-23T18:22:00Z',
    modelVersion: 'FG-4.2.1-PROD',
    customer: 'Sneha Patel',
    location: 'Ahmedabad, IN',
    paymentMethod: 'UPI (GPay)',
    device: 'iPhone 15 Pro',
    factors: [],
  },
  {
    id: 'TXN_829388',
    amount: 18500,
    prediction: 'Legitimate',
    fraudProbability: 14.5,
    anomalyScore: 0.16,
    riskScore: 18,
    riskLevel: 'LOW',
    timestamp: '2025-08-23T18:15:00Z',
    modelVersion: 'FG-4.2.1-PROD',
    customer: 'Vikram Sengupta',
    location: 'Kolkata, IN',
    paymentMethod: 'Axis Bank Debit',
    device: 'Chrome Windows 11',
    factors: [],
  },
  {
    id: 'TXN_829387',
    amount: 490000,
    prediction: 'Fraud',
    fraudProbability: 96.8,
    anomalyScore: 0.94,
    riskScore: 97,
    riskLevel: 'CRITICAL',
    timestamp: '2025-08-23T18:02:00Z',
    modelVersion: 'FG-4.2.1-PROD',
    customer: 'Ananya Rao',
    location: 'Singapore, SG',
    paymentMethod: 'Amex Platinum (..1004)',
    device: 'TOR Exit Node',
    factors: defaultFactors,
  },
  {
    id: 'TXN_829386',
    amount: 980,
    prediction: 'Legitimate',
    fraudProbability: 3.2,
    anomalyScore: 0.04,
    riskScore: 5,
    riskLevel: 'LOW',
    timestamp: '2025-08-23T17:48:00Z',
    modelVersion: 'FG-4.2.1-PROD',
    customer: 'Devam Dadhia',
    location: 'Mumbai, IN',
    paymentMethod: 'UPI (PhonePe)',
    device: 'MacBook Air M3',
    factors: [],
  },
];

export const alerts: Alert[] = [
  {
    ...transactions[0],
    status: 'Open',
    triggerReason: 'High Transaction Amount + Geo Anomaly',
    assignedTo: 'Admin (You)',
  },
  {
    ...transactions[1],
    status: 'Reviewing',
    triggerReason: 'Velocity rule triggered: 4 rapid txns',
    assignedTo: 'Kavita Joshi',
  },
  {
    ...transactions[2],
    status: 'Open',
    triggerReason: 'Sudden international IP switch to UAE',
    assignedTo: 'Unassigned',
  },
  {
    ...transactions[5],
    status: 'Reviewing',
    triggerReason: 'Critical amount on TOR Network node',
    assignedTo: 'Admin (You)',
  },
];

export const recentAlerts: RecentAlert[] = [
  {
    id: 'alt_1',
    transactionId: 'TXN_829392',
    title: 'High Risk Transaction',
    amount: 245000.0,
    riskLevel: 'High',
    timestamp: '2 min ago',
    type: 'transaction',
  },
  {
    id: 'alt_2',
    transactionId: 'TXN_829391',
    title: 'Velocity Rule Triggered',
    amount: 75000.0,
    riskLevel: 'Medium',
    timestamp: '8 min ago',
    type: 'velocity',
  },
  {
    id: 'alt_3',
    transactionId: 'TXN_829390',
    title: 'Unusual Location',
    amount: 120000.0,
    riskLevel: 'Medium',
    timestamp: '15 min ago',
    type: 'location',
  },
  {
    id: 'alt_4',
    transactionId: 'USR_938291',
    title: 'New Device Login',
    amount: 0,
    riskLevel: 'Low',
    timestamp: '19 min ago',
    type: 'device',
  },
];

export const topRiskFactors: RiskFactor[] = [
  {
    name: 'High Transaction Amount',
    percentage: 32,
    color: '#ef4444',
    count: 142,
  },
  {
    name: 'Unusual Location',
    percentage: 24,
    color: '#f59e0b',
    count: 106,
  },
  {
    name: 'Rapid Transactions',
    percentage: 18,
    color: '#3b82f6',
    count: 80,
  },
  {
    name: 'New Device',
    percentage: 14,
    color: '#10b981',
    count: 62,
  },
  {
    name: 'Other Factors',
    percentage: 12,
    color: '#8b5cf6',
    count: 53,
  },
];

export const riskTrendData: RiskTrendItem[] = [
  { date: '17 Aug', score: 25, riskLevel: 'Low', color: '#10b981' },
  { date: '18 Aug', score: 36, riskLevel: 'Low', color: '#10b981' },
  { date: '19 Aug', score: 48, riskLevel: 'Medium', color: '#f59e0b' },
  { date: '20 Aug', score: 58, riskLevel: 'Medium', color: '#f59e0b' },
  { date: '21 Aug', score: 52, riskLevel: 'Medium', color: '#f59e0b' },
  { date: '22 Aug', score: 68, riskLevel: 'High', color: '#f97316' },
  { date: '23 Aug', score: 86, riskLevel: 'High', color: '#ef4444' },
];

export const sparklineData = {
  transactions: [
    { v: 10400 },
    { v: 10900 },
    { v: 11500 },
    { v: 11200 },
    { v: 11900 },
    { v: 12200 },
    { v: 12589 },
  ],
  flagged: [
    { v: 180 },
    { v: 195 },
    { v: 210 },
    { v: 205 },
    { v: 228 },
    { v: 242 },
    { v: 256 },
  ],
  fraud: [
    { v: 28 },
    { v: 31 },
    { v: 33 },
    { v: 30 },
    { v: 37 },
    { v: 39 },
    { v: 42 },
  ],
  amount: [
    { v: 6.8 },
    { v: 7.1 },
    { v: 7.4 },
    { v: 7.9 },
    { v: 8.1 },
    { v: 8.4 },
    { v: 8.74 },
  ],
};

export const analytics: Analytics = {
  totalTransactions: 12589,
  fraudTransactions: 42,
  highCriticalAlerts: 256,
  fraudRate: 0.33,
  averageRiskScore: 23.0,
  totalAmountAnalyzed: 87400000,
  fraudSplit: [
    { name: 'Legitimate', value: 12547 },
    { name: 'Fraud', value: 42 },
  ],
  riskDistribution: [
    { name: 'Low Risk', value: 62, color: '#10b981' },
    { name: 'Medium Risk', value: 23, color: '#f59e0b' },
    { name: 'High Risk', value: 15, color: '#ef4444' },
  ],
  activity: [
    { time: '17 Aug', transactions: 1540, flagged: 22 },
    { time: '18 Aug', transactions: 1680, flagged: 29 },
    { time: '19 Aug', transactions: 1790, flagged: 34 },
    { time: '20 Aug', transactions: 1820, flagged: 41 },
    { time: '21 Aug', transactions: 1910, flagged: 38 },
    { time: '22 Aug', transactions: 1960, flagged: 44 },
    { time: '23 Aug', transactions: 1889, flagged: 48 },
  ],
};

export const initialMessages: ChatMessage[] = [
  {
    id: 'm-intro',
    role: 'assistant',
    content:
      "Hi Admin! I'm your AI Assistant. I can help you analyze data, explain risks, and generate insights.",
    timestamp: '18:40',
  },
];

export const customersList: Customer[] = [
  {
    id: 'CUST-901',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@domain.in',
    riskScore: 89,
    riskLevel: 'HIGH',
    totalTransactions: 48,
    flaggedCount: 3,
    lastActive: '2 min ago',
    device: 'Linux / Chrome',
    location: 'Mumbai, IN',
  },
  {
    id: 'CUST-902',
    name: 'Rohan Mehta',
    email: 'rohan.mehta@enterprise.com',
    riskScore: 68,
    riskLevel: 'MEDIUM',
    totalTransactions: 112,
    flaggedCount: 2,
    lastActive: '8 min ago',
    device: 'Android 14',
    location: 'Bengaluru, IN',
  },
  {
    id: 'CUST-903',
    name: 'Priya Nair',
    email: 'priya.nair@globaltrade.ae',
    riskScore: 58,
    riskLevel: 'MEDIUM',
    totalTransactions: 64,
    flaggedCount: 1,
    lastActive: '15 min ago',
    device: 'macOS / Safari',
    location: 'Dubai, UAE',
  },
  {
    id: 'CUST-904',
    name: 'Sneha Patel',
    email: 'sneha.patel@outlook.com',
    riskScore: 12,
    riskLevel: 'LOW',
    totalTransactions: 284,
    flaggedCount: 0,
    lastActive: '22 min ago',
    device: 'iOS / Safari',
    location: 'Ahmedabad, IN',
  },
  {
    id: 'CUST-905',
    name: 'Vikram Sengupta',
    email: 'vikram.sen@fintech.co',
    riskScore: 18,
    riskLevel: 'LOW',
    totalTransactions: 95,
    flaggedCount: 0,
    lastActive: '34 min ago',
    device: 'Windows 11',
    location: 'Kolkata, IN',
  },
];

export const rulesList: FraudRule[] = [
  {
    id: 'RULE-101',
    name: 'High Amount Velocity Spike',
    type: 'Velocity & Amount',
    condition: 'Amount > ₹1,50,000 within 10 min window',
    threshold: '> ₹1,50,000 / 10m',
    action: 'Flag',
    enabled: true,
    lastTriggered: '2 min ago',
  },
  {
    id: 'RULE-102',
    name: 'Impossible Geolocation Jump',
    type: 'Geo-Distance',
    condition: 'Distance > 800 km in < 30 minutes',
    threshold: '> 800 km / 30m',
    action: 'Block',
    enabled: true,
    lastTriggered: '15 min ago',
  },
  {
    id: 'RULE-103',
    name: 'Known TOR Exit Node Access',
    type: 'Network Anomaly',
    condition: 'IP matches updated TOR / VPN blacklists',
    threshold: 'Risk Score >= 85',
    action: 'Block',
    enabled: true,
    lastTriggered: '38 min ago',
  },
  {
    id: 'RULE-104',
    name: 'First-Time Device International Attempt',
    type: 'Device & Geo',
    condition: 'New Device ID + Country != Home Country',
    threshold: 'Confidence < 40%',
    action: 'Review',
    enabled: true,
    lastTriggered: '1 hr ago',
  },
];

export const reportsList: FraudReport[] = [
  {
    id: 'REP-2025-W34',
    title: 'Weekly Fraud Risk Intelligence Report',
    dateRange: '17 Aug – 23 Aug 2025',
    generatedAt: 'Today at 18:00',
    format: 'PDF',
    size: '2.4 MB',
    riskSummary: '42 Fraud incidents blocked (₹8.74 Cr protected)',
  },
  {
    id: 'REP-2025-W33',
    title: 'Weekly Fraud Risk Intelligence Report',
    dateRange: '10 Aug – 16 Aug 2025',
    generatedAt: '16 Aug 2025',
    format: 'PDF',
    size: '2.1 MB',
    riskSummary: '33 Fraud incidents blocked (₹7.18 Cr protected)',
  },
  {
    id: 'REP-2025-M07',
    title: 'Monthly Regulatory Compliance & Audit Log',
    dateRange: '01 Jul – 31 Jul 2025',
    generatedAt: '01 Aug 2025',
    format: 'CSV',
    size: '14.8 MB',
    riskSummary: '100% SLA compliance for high severity alerts',
  },
];
