# ============================================================
# FinGuard AI
# GenAI Assistant API Schemas
# ============================================================

from pydantic import BaseModel, Field


# ============================================================
# Assistant Request
# ============================================================

class AssistantRequest(BaseModel):
    """
    User message sent to the FinGuard AI Assistant.
    """

    question: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="User's question for the fraud analyst assistant"
    )

    transaction_id: str | None = Field(
        default=None,
        description="Optional transaction ID for transaction-specific questions"
    )


# ============================================================
# Assistant Response
# ============================================================

class AssistantResponse(BaseModel):
    """
    Response generated by the FinGuard AI Assistant.
    """

    answer: str

    transaction_id: str | None = None

    model: str

    success: bool = True